<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Manoj" failures="4" tests="5" name="Default test" time="413.925" errors="0" timestamp="2023-07-12T20:33:43 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="69.207">
    <failure type="org.openqa.selenium.WebDriverException" message="chrome not reachable
Build info: version: &amp;apos;3.141.5&amp;apos;, revision: &amp;apos;d54ebd709a&amp;apos;, time: &amp;apos;2018-11-06T11:42:16&amp;apos;
System info: host: &amp;apos;MANOJ&amp;apos;, ip: &amp;apos;192.168.43.97&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.3&amp;apos;
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	GetHandleVerifier [0x00C6A813+48355]
	(No symbol) [0x00BFC4B1]
	(No symbol) [0x00B05220]
	(No symbol) [0x00AFB355]
	(No symbol) [0x00B25C68]
	(No symbol) [0x00B21EF3]
	(No symbol) [0x00B20579]
	(No symbol) [0x00B50C55]
	(No symbol) [0x00B5093C]
	(No symbol) [0x00B4A536]
	(No symbol) [0x00B282DC]
	(No symbol) [0x00B293DD]
	GetHandleVerifier [0x00ECAABD+2539405]
	GetHandleVerifier [0x00F0A78F+2800735]
	GetHandleVerifier [0x00F0456C+2775612]
	GetHandleVerifier [0x00CF51E0+616112]
	(No symbol) [0x00C05F8C]
	(No symbol) [0x00C02328]
	(No symbol) [0x00C0240B]
	(No symbol) [0x00BF4FF7]
	BaseThreadInitThunk [0x75D400C9+25]
	RtlGetAppContainerNamedObjectPath [0x774E7B4E+286]
	RtlGetAppContainerNamedObjectPath [0x774E7B1E+238]
">
      <![CDATA[org.openqa.selenium.WebDriverException: chrome not reachable
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:42:16'
System info: host: 'MANOJ', ip: '192.168.43.97', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.3'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
GetHandleVerifier [0x00C6A813+48355]
(No symbol) [0x00BFC4B1]
(No symbol) [0x00B05220]
(No symbol) [0x00AFB355]
(No symbol) [0x00B25C68]
(No symbol) [0x00B21EF3]
(No symbol) [0x00B20579]
(No symbol) [0x00B50C55]
(No symbol) [0x00B5093C]
(No symbol) [0x00B4A536]
(No symbol) [0x00B282DC]
(No symbol) [0x00B293DD]
GetHandleVerifier [0x00ECAABD+2539405]
GetHandleVerifier [0x00F0A78F+2800735]
GetHandleVerifier [0x00F0456C+2775612]
GetHandleVerifier [0x00CF51E0+616112]
(No symbol) [0x00C05F8C]
(No symbol) [0x00C02328]
(No symbol) [0x00C0240B]
(No symbol) [0x00BF4FF7]
BaseThreadInitThunk [0x75D400C9+25]
RtlGetAppContainerNamedObjectPath [0x774E7B4E+286]
RtlGetAppContainerNamedObjectPath [0x774E7B1E+238]

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
at stepDefinitions.checkLoginDefinitions.thatIHaveGoneToTheOPENHRMPage(checkLoginDefinitions.java:21)
at ✽.that I have gone to the OPENHRM page(file:///C:/Users/user/eclipse-workspace/CucumberPractice/src/test/java/featureFiles/checkLogin.feature:5)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="149.2"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="67.285">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefinitions.checkLoginDefinitions.loginShouldHappenAndShouldGetFecthedCorrectlyInThePage(checkLoginDefinitions.java:48)
at ✽.login should happen and "https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index" should get fecthed correctly in the page(file:///C:/Users/user/eclipse-workspace/CucumberPractice/src/test/java/featureFiles/checkLogin.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="54.333">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefinitions.checkLoginDefinitions.loginShouldHappenAndShouldGetFecthedCorrectlyInThePage(checkLoginDefinitions.java:48)
at ✽.login should happen and "https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index" should get fecthed correctly in the page(file:///C:/Users/user/eclipse-workspace/CucumberPractice/src/test/java/featureFiles/checkLogin.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="58.355">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefinitions.checkLoginDefinitions.loginShouldHappenAndShouldGetFecthedCorrectlyInThePage(checkLoginDefinitions.java:48)
at ✽.login should happen and "https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index" should get fecthed correctly in the page(file:///C:/Users/user/eclipse-workspace/CucumberPractice/src/test/java/featureFiles/checkLogin.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
